Controllers/ListAllContactsController.cs
using InformationManagementMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;

namespace InformationManagementMVC.Controllers
{
    public class ListAllContactsController : Controller
    {
        // GET: ListAllContacts
        public  ActionResult Index(int? pageIndex)
        {
            int pageSize = 10;
            pageIndex = pageIndex.HasValue ? Convert.ToInt32(pageIndex) : 1;
            IList<CallList> cll1 = null;
            string baseAddress = "http://localhost:62829";
            string AccessToken = HttpContext.Session["AccessToken"].ToString();
            double UserID = double.Parse(HttpContext.Session["UserID"].ToString());
            using (HttpClient httpClient1 = new HttpClient())
            {
                httpClient1.BaseAddress = new Uri(baseAddress);
                httpClient1.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("bearer", AccessToken);
                var responseTask = httpClient1.GetAsync("api/ListAllContacts/GetCallList?pageNumber=" + pageIndex.ToString());
                // New code:
                if (responseTask.Result.IsSuccessStatusCode)
                {

                    responseTask.Wait();
                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<IList<CallList>>();
                        cll1 = readTask.Result;
                        return View(cll1.ToPagedList(pageIndex??1,pageSize));
                    }
                    else
                    {
                        cll1 = null;
                        ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                        return View(cll1.ToPagedList(pageIndex??1,pageSize));
                    }
                }
            }
            return View(cll1);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Information Management System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <div class="container-fluid">
                    <ul class="nav navbar-nav">
                        @*<li>@Html.ActionLink("Call List", "Index", "CallList", new { UserID = @Session["UserID"] })</li>*@
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Call List", "PopulateCallList", "Home")</li>
                        <li>@Html.ActionLink("All Contact List", "Index", "ListAllContacts")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><span class="glyphicon glyphicon-log-out">@Html.ActionLink("Logout", "Logout", "Home")</span> </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>