Controllers/LoginController.cs
using IdentityModel.Client;
using InformationManagementMVC.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using ZendeskApi_v2.Models.Articles;

namespace InformationManagementMVC.Controllers
{
    public class LoginController : Controller
    {
        //private object token;
        public ActionResult LoginPage()       
        {
            return View();
        }
        [HttpPost]
        public ActionResult LoginPage(RegisterUser reg)
        {
            IEnumerable<RegisterUser> RegUsr = null;
            string baseAddress = "http://localhost:62829";
            using (var client = new HttpClient())
            {
                var form = new Dictionary<string, string>
               {
                   {"grant_type", "password"},
                   {"username", reg.UserName},
                   {"password", reg.PassWord}
               };
                int regid =Convert.ToInt32(TempData["Regid"]);
                var tokenResponse = client.PostAsync(baseAddress + "/token", new FormUrlEncodedContent(form)).Result;
                var token = tokenResponse.Content.ReadAsAsync<Token>().Result;
                using (HttpClient httpClient1 = new HttpClient())
                {
                    httpClient1.BaseAddress = new Uri(baseAddress);
                    httpClient1.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("bearer", token.AccessToken);
                    HttpResponseMessage response= httpClient1.GetAsync("api/Login/LoginAllUsers").Result;
                    var responseTask = httpClient1.GetAsync("api/Login/LoginAllUsers");
                    responseTask.Wait();
                    var result = responseTask.Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<IList<RegisterUser>>();
                        readTask.Wait();

                        RegUsr = readTask.Result;
                        System.Console.WriteLine("Success");
                        string message = response.Content.ReadAsStringAsync().Result;
                        var json1 = JsonConvert.DeserializeObject(message);
                        Session["AccessToken"] = token.AccessToken;
                        if (Session["AccessToken"] != null)
                        {
                            double uid = 0;
                            foreach (var u in RegUsr)
                            {
                                uid = u.Id;
                                Session["UserID"] = u.Id;
                            }
                            return RedirectToAction("Index", "CallList", new { UserID = Session["UserID"] });
                        }
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Please login with correct UserName and Password");
                    }
                }
                return View(reg);
            }
        }
        public ActionResult Logout()
        {
            Session["AccessToken"] = null;
            Session["UserID"] = null;
            Session.Abandon();
            return RedirectToAction("Login");
        }
    }
}

Controllers/RegisterUserController.cs
using InformationManagementMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace InformationManagementMVC.Controllers
{
    public class RegisterUserController : Controller
    {
        // GET: RegisterUser
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult create(RegisterUser reg)
        {
            string baseAddress = "http://localhost:62829";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseAddress);
                var postTask = client.PostAsJsonAsync<RegisterUser>("api/RegisterUser/EditRegList", reg);
                postTask.Wait();
                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    TempData["success"] = "Registered Successfully, Please enter your UserName and Password for login";
                    TempData["Regid"] = reg._id;
                    return RedirectToAction("LoginPage", "Login", new { _id = reg._id });
                }
                else
                {
                    if (result.StatusCode == System.Net.HttpStatusCode.Conflict)
                    {
                        ModelState.AddModelError(string.Empty, "User already exist");
                        return View(reg);
                    }
                }
            }
            ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");
            return View(reg);
        }
    }
}

Views/Login/Login.cshtml
@model InformationManagementMVC.Models.RegisterUser

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegisterUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.PassWord, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Login/LoginPage.cshtml
@model InformationManagementMVC.Models.RegisterUser

@{
    ViewBag.Title = "Login";
}
@{
    Layout = null;
}
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h2>Login</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="alert-success">
            @TempData["success"]
            <div></div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control-lg" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.PassWord, htmlAttributes: new { @class = "form-control-lg" })
                @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
            </div>
            @Html.HiddenFor(model => model._id, htmlAttributes: new { @class = "control-label col-md-2" })

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-success" />
            </div>
        </div>
        <div class="form-group">
            <label id="msg"></label>
            <div></div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("New User", "create", "RegisterUser")
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}